### PR TITLE
Remove unmaintained `ansi_term` dependency

### LINKED ISSUE #502: RUSTSEC-2021-0139: ansi_term is Unmaintained
> ansi_term is Unmaintained

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `ansi_term`                      |
| Version             | `0.12.1`                   |
| URL                 | [https://github.com/ogham/rust-ansi-term/issues/72](https://github.com/ogham/rust-ansi-term/issues/72) |
| Date                | 2021-08-18                         |

The maintainer has adviced this crate is deprecated and will not
receive any maintenance.

The crate does not seem to have much dependencies and may or may not be ok to use as-is.

Last release seems to have been three years ago.

## Possible Alternative(s)

 The below list has not been vetted in any way and may or may not contain alternatives;

 - [anstyle](https://github.com/epage/anstyle)
 - [nu-ansi-term](https://crates.io/crates/nu-ansi-term)
 - [yansi](https://crates.io/crates/yansi)

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2021-0139.html) for additional details.

### PR DESCRIPTION
**Pull request by kate-goldenring**
**What this PR does / why we need it**:
fixes #502 by bumping webhook's `clap` version to latest which was previously pulling in the unmaintained dependency

**If applicable**:
- [x] version has been updated appropriately (`./version.sh`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Comment by adithyaj** [comment]
great simple fix for this issue, looks good to me :shipit:

**Comment by kate-goldenring** [comment]
Looks like in the e2e tests we are failing to spin up a K8s v1.16 cluster. We probably need to change the install script, but better yet, i think it may be time to remove older versions of k8s from the test matrix. This could be part of the release steps. @bfjelds and @adithyaj, thoughts?

**Comment by adithyaj** [comment]
> Looks like in the e2e tests we are failing to spin up a K8s v1.16 cluster. We probably need to change the install script, but better yet, i think it may be time to remove older versions of k8s from the test matrix. This could be part of the release steps. @bfjelds and @adithyaj, thoughts?

Yup this seems to be affecting #508 too. I believe all the kubernetes versions in our test matrix (1.16-1.21) are [at EOL](https://kubernetes.io/releases/patch-releases/#non-active-branch-history). Let's maybe test against the latest EOL version and the rest of the active supported branches (1.21-1.25)? We can also update the release process to check for this.


@michaelzhang114 let's talk about it as a quick agenda item as part of the release for [tomorrow's community meeting](https://aka.ms/akri/meeting-notes).

**Review by adithyaj — APPROVED** [review]
looks good to me, and the version got bumped 0.8.20 so we can merge this now

**Comment by kate-goldenring** [comment]
> looks good to me, and the version got bumped 0.8.20 so we can merge this now

we need a maintainer approval to merge. @bfjelds @romoh

**Pull request merged**
