### PR TITLE
Fix unix domain socket (uds) gRPC-client implementation compatibility with Googles' C based gRPC (reference) implementation (closes #497)

### LINKED ISSUE #497: Unix domain socket (uds) gRPC-client implementation incompatible with Googles' C based gRPC (reference) implementation
**Describe the bug**
The unix domain socket implementation of the gRPC-client is incompatible with servers implemented using Googles' C based gRPC implementation. As this implementation is the base for most non-native implementations, it may be considered a **reference implementation** and this behavior is likely to be observable in a number of languages.

Discovery handlers implement the gRPC DiscoveryHandler service (as server) to be called by the akri agent. Using a unix domain socket as transport yields the following errors:
(C++ implementation; gRPC `1.48.0`; akri `0.8.4`):
```
# grpc server C++ / discovery handler
E0816 09:31:06.619375200      14 hpack_parser.cc:1235]       Error parsing metadata: error=invalid value key=:scheme value=dummy

# akri agent
[2022-08-16T09:31:06Z ERROR agent::util::discovery_operator] get_stream - could not connect to DiscoveryHandler at endpoint Uds("/var/lib/akri/demo-disco.sock") with error status: Unknown, message: "Bad :scheme header", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

***Analysis***
akri connects a gRPC-client over uds by instantiating a `tonic::transport::Endpoint` from a/the valid URL string `"dummy://[::]:50051"` and providing a `UnixStream` instance for the connection. *tonic* sets the `scheme` header from the URL provided at instantiation time, which results in `scheme: dummy`.  The C based implementation will reject all requests without `scheme` headers set to `http` or `https`:

https://github.com/grpc/grpc/blob/f268659bf183a39857064593b141f313845282d9/src/core/lib/transport/metadata_batch.cc#L150-L159

> *tonic* clients connecting over network are unaffected as all URLs are prefixed with `http://` in the current akri implementation

***Fix***
Replacing all instantiations of `tonic::transport::Endpoint` with URL `"dummy://[::]:50051"` to `"http://[::]:50051"`.

**See #498**

**To Reproduce**
* Build gRPC server listening on unix domain socket; using Google C based gRPC implementation
* Build rust gRPC client connecting to server over unix domain socket with akri-like implementation

**Expected behavior**
gRPC communication working and no errors thrown. I.e.: Scheme header set correctly.

**Logs (please share snips of applicable logs)**
```
# grpc server C++ / discovery handler
E0816 09:31:06.619375200      14 hpack_parser.cc:1235]       Error parsing metadata: error=invalid value key=:scheme value=dummy

# akri agent
[2022-08-16T09:31:06Z ERROR agent::util::discovery_operator] get_stream - could not connect to DiscoveryHandler at endpoint Uds("/var/lib/akri/demo-disco.sock") with error status: Unknown, message: "Bad :scheme header", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

### PR DESCRIPTION
**Pull request by bitmeal**
**What this PR does / why we need it**:
closes #497 (*at least fixes it*)

**Special notes for your reviewer**:
* has been tested in isolation, and in a cluster with a custom discovery handler using the google C++ gRPC implementation
* ~~test `discovery::server::tests::test_run_discovery_server_error_invalid_ip_addr` is failing (for me) even without the modifications and a clean *master* branch.~~

**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [x] inline documentation builds (`cargo doc`)
- [x] version has been updated appropriately (`./version.sh`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Comment by kate-goldenring** [comment]
This seems like a great fix to me. I just kicked off the end to end tests. Assuming those pass, I think it is safe assume that going from `dummy` to `http` is a fair change.

> test discovery::server::tests::test_run_discovery_server_error_invalid_ip_addr is failing (for me) even without the modifications and a clean master branch.
@bitmeal what errors are you getting when you run the test?

**Comment by bitmeal** [comment]
`cargo test` fails `discovery::server::tests::test_run_discovery_server_error_invalid_ip_addr` from master branch (and with the modifications from the pull request) on
* Ubuntu 20.04 on WSL2 with latest rust version
* Ubuntu 18.04 with rust version set by the setup script

**Comment by kate-goldenring** [comment]
> `cargo test` fails `discovery::server::tests::test_run_discovery_server_error_invalid_ip_addr` from master branch (and with the modifications from the pull request) on
> 
> * Ubuntu 20.04 on WSL2 with latest rust version
> * Ubuntu 18.04 with rust version set by the setup script

@bitmeal does it give any extra output? Can you run it with `RUST_LOG=trace` and `-- --nocapture`

**Comment by bitmeal** [comment]
Seems to be **my fault**: Rust toolchain versions have not been set correctly while running tests!
Tests succeed without any issues when using `1.61.0` version (tested @ Ubuntu *Bionic*, *Focal* and *Jammy*).

*I will edit the PR text to reflect the info*
---

> @bitmeal does it give any extra output? Can you run it with `RUST_LOG=trace` and `-- --nocapture`

Using latest `stable` toolchain does yield the error though. While this is then not related to this PR anymore, I uploaded the requested logs here: https://gist.github.com/bitmeal/c7dde39407a2c9ecb44b48307633310a
* produced with: `RUST_LOG=trace cargo test -- --nocapture 2>&1 | tee cargo_test_trace.log`
* `cargo --version` → `cargo 1.63.0 (fd9c4297c 2022-07-01)`
* `uname -a` → `Linux 5a3c77f245ae 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kate-goldenring** [comment]
> Seems to be **my fault**: Rust toolchain versions have not been set correctly while running tests! Tests succeed without any issues when using `1.61.0` version (tested @ Ubuntu _Bionic_, _Focal_ and _Jammy_).

@bitmeal this is a good bump on us. We should put out a new release and bump our rust version soon.

**Comment by kate-goldenring** [comment]
@bitmeal looks like our tarpaulin workflow is running into the same issue you had and failing: https://github.com/project-akri/akri/issues/501
I dont think that blocks this merging. Lets get at least one more eye on this: @bfjelds @romoh @michaelzhang114

**Comment by adithyaj** [comment]
This is a great catch and looks good to me and with @bfjelds fix (#501) we should be good to merge this now.

**Review by kate-goldenring — APPROVED** [review]
Thanks @bitmeal!

**Comment by bitmeal** [comment]
> Thanks @bitmeal!

Thanks to you for the good work!

**Pull request merged**
