### PR TITLE
Rust toolchain update to 1.63.0

### PR DESCRIPTION
**Pull request by adithyaj**
**What this PR does / why we need it**:
- Updates rust toolchain to 1.63.0

**Special notes for your reviewer**:
- Tarpaulin was kept at 0.20.1 as it is the latest available container on Docker Hub even though there was a 0.21.0 released on GitHub. If there is an updated container + tag on Docker Hub before this gets PR gets merged I can update and retest.
- Used the _CARGO_VERSION_ environment variable in run tarpaulin action so we can refer to that globally (instead of hardcoding during the install)
- Since we have autogenerated code with prost, there's an [issue ](https://github.com/tokio-rs/prost/issues/661) where it does not derive Eq along with PartialEq. Until this is fixed we have to disable the lint check for it

**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [x] inline documentation builds (`cargo doc`)
- [ ] version has been updated appropriately (`./version.sh`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Comment by adithyaj** [comment]
minor rust changes needed along with the version bump, I'll get those in and push it out.

**Comment by kate-goldenring** [comment]
> some rust changes needed along with the version bump, I'll get those in

@adithyaj looks like there are a lot of clippy errors that were caught in the version bump that can be addressed in this PR

**Comment by adithyaj** [comment]
@kate-goldenring I rebased and this is good to go as well!

FYI I did get a DCO notification about prior commits from my rebase:
> Commit sha: [2ac813d](https://github.com/project-akri/akri/pull/507/commits/2ac813d7a0fdb08716905108d47257a385b004f7), Author: Karapet Kostandyan, Committer: GitHub; Expected "Karapet Kostandyan [karapet.kostandyan@gmail.com](mailto:karapet.kostandyan@gmail.com)", but got "Karapet Kostandyan [kakostan@microsoft.com](mailto:kakostan@microsoft.com)".
Commit sha: [ec3999f](https://github.com/project-akri/akri/pull/507/commits/ec3999fccb4171a7c452371b22e9ca6abd27eb50), Author: Karapet Kostandyan, Committer: GitHub; Expected "Karapet Kostandyan [karapet.kostandyan@gmail.com](mailto:karapet.kostandyan@gmail.com)", but got "Karapet Kostandyan [kakostan@microsoft.com](mailto:kakostan@microsoft.com)".

I'll squash the commits to make sure it doesn't stick on this change but I'm not sure how the PR passed DCO before on those commits.

**Comment by adithyaj** [comment]
validated by vtam-msft but not yet on the owners.txt.
merging to unblock release and will update owners.txt in separate file

**Pull request merged**
