### PR TITLE
Upgrade from Buster to Bullseye Docker images

### PR DESCRIPTION
**Pull request by jbpaux**
**What this PR does / why we need it**:
Upgrade container images to Bullseye (with the exception of the intermediate opencv container image)
Part of #606 
**Special notes for your reviewer**:
I'll have a look if doc need to be updated.

**If applicable**:
- [x] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [ ] added code adheres to standard Rust formatting (`cargo fmt`)
- [ ] code builds properly (`cargo build`)
- [ ] code is free of common mistakes (`cargo clippy`)
- [ ] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Review by kate-goldenring — APPROVED** [review]

**Comment by jbpaux** [comment]
Don't merge it before I update the `USE_OPENCV_BASE_VERSION` after intermediate image has been pushed

**Comment by kate-goldenring** [comment]
> Don't merge it before I update the USE_OPENCV_BASE_VERSION after intermediate image has been pushed

@jbpaux, https://github.com/project-akri/akri/pull/609 is merged. should be good to update `USE_OPENCV_BASE_VERSION`

**Comment by jbpaux** [comment]
it should be good but I think the previous intermediate image hasn't been pushed so this one if failing. Maybe the github action is not triggering push well ?

**Comment by diconico07** [comment]
Indeed the github action skipped the build and push part on merge :unamused: , will do a PR to fix that behavior and then build those containers.

**Comment by jbpaux** [comment]
Feel free to update version and merge :)

**Pull request merged**
