### PR TITLE
added extra casting for opc plc demo

### LINKED ISSUE #526: Update OPC UA demo to use containerized PLC server
The [OPC UA end-to-end demo](https://docs.akri.sh/demos/opc-thermometer-demo) should be updated to use the [OPC PLC server](https://github.com/azure-samples/iot-edge-opc-plc/) rather than requiring users to build and run demo servers as currently done.

#464 has instructions for how to use the PLC server in conjunction with Akri.

Would be great to update the [demo doc](https://github.com/project-akri/akri-docs/blob/main/docs/demos/opc-thermometer-demo.md) or create a new demo! The sample broker and app may need slight modifications.

### PR DESCRIPTION
**Pull request by harrison-tin**
**What this PR does / why we need it**:
The new OPC PLC demo (can update the official doc once this PR is approved) uses [OPC PLC server](https://github.com/azure-samples/iot-edge-opc-plc/) which comes with its own simulated value. We can configure their fast and slow nodes which have the [data types](https://github.com/azure-samples/iot-edge-opc-plc/#data-types) uint, double, bool, and uint array. Since currently the anomaly detection app supports integer, I chose to use uint which requires casting the data value to uint first, then cast it to integer and pass to the gRPC interface.

it closes #526 
**Special notes for your reviewer**:

**If applicable**:
- [x] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [ ] added code adheres to standard Rust formatting (`cargo fmt`)
- [ ] code builds properly (`cargo build`)
- [ ] code is free of common mistakes (`cargo clippy`)
- [ ] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [ ] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Comment by kate-goldenring** [comment]
@harrison-tin just need to sign your commit and then this LGTM. see the DCO bot action for steps

**Comment by harrison-tin** [comment]
@kate-goldenring thanks for the reminder. Just signed the commit. Once it's approved, I will sync with Yu Jin to update the demo.

**Review by kate-goldenring — APPROVED** [review]

**Comment by yujinkim-msft** [comment]
https://github.com/project-akri/akri-docs/pull/56 :  updated docs to go along with this change has been approved.

**Pull request merged**
