### PR TITLE
Fix incorrect Onvif filter

### LINKED ISSUE #597: Onvif discovery Handler incorrectly filter ip address
**Describe the bug**
set filter ip address to exclude 10.0.0.1 will end up filtering all ip addresses start with 10.0.0.1, including 10.0.0.1xx.

**To Reproduce**
1. Create cluster
2. Install Akri with the Helm command and deploy the Akri Configuration yaml modified from test/yaml/akri-onvif-video-configuration.yaml (see below).  In the configuration, only exclude cameras with ip address 10.0.0.1, 10.0.0.2.
3. My Onvif camera ip is 10.0.0.107, after deploying the Configuration, my camera is not detected.

apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-onvif-video
spec:
  discoveryHandler:
    name: onvif
    discoveryDetails: |+
        ipAddresses:
          action: Exclude
          items:
          - 10.0.0.1
          - 10.0.0.2
        macAddresses:
          action: Exclude
          items: []
        scopes:
          action: Exclude
          items: []
        discoveryTimeoutSeconds: 2
  brokerSpec:
    brokerPodSpec:
      containers:
      - name: akri-onvif-video-broker
        image: "ghcr.io/project-akri/akri/onvif-video-broker:latest-dev"
        imagePullPolicy: Always
        resources:
          limits:
            "{{PLACEHOLDER}}" : "1"
  instanceServiceSpec:
    ports:
    - name: grpc
      port: 80
      targetPort: 8083
  configurationServiceSpec:
    ports:
    - name: grpc
      port: 80
      targetPort: 8083
  brokerProperties: {}

**Expected behavior**
Onvif camera ip address 10.0.0.107 discovered.
Onvif discovery handler should only filter out 10.0.0.1 and 10.0.0.2, not others.

### PR DESCRIPTION
**Pull request by jbpaux**
**What this PR does / why we need it**:
Fix #597 issue by changing incorrect contains to equality
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [x] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Review by kate-goldenring — APPROVED** [review]
Thanks for the find and fix!

**Review by diconico07 — APPROVED** [review]

**Comment by diconico07** [comment]
Okay, hoped the bot would do magic here, but no. Can you rebase @jbpaux so we have right patch version upgrade and can merge this.

**Pull request merged**
