### PR TITLE
Use `containerd` as default container runtime socket for standard Kubernetes

### LINKED ISSUE #455: Switch to using `containerd` as default container runtime socket for standard Kubernetes
**Current state**
Currently if a user specifies they are using standard Kuberntes (`--set kubernetesDistro=K8s`), then [Akri assumes](https://github.com/project-akri/akri/blob/main/deployment/helm/values.yaml#L104) the container runtime socket to be at `/var/run/dockershim.sock`. This should be changed to `/run/containerd/containerd.sock` as Docker as the underlying runtime in K8s [has been deprecated](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) in favor of CRI runtimes like containerd.

**Describe the solution you'd like**
Update the defaults in the helm templates [like in the Agent template here](https://github.com/project-akri/akri/blob/main/deployment/helm/templates/agent.yaml#L113), update [end to end test pipeline](https://github.com/project-akri/akri/blob/main/.github/workflows/run-test-cases.yml#L214) to ensure that K8s installation has been updated to use containerd, and update the Akri [cluster setup documentation](https://github.com/project-akri/akri-docs/blob/main/docs/user-guide/cluster-setup.md).

### PR DESCRIPTION
**Pull request by Rishit-dagli**
**What this PR does / why we need it**:

Akri by default assumes the container runtime socket to be at `/var/run/dockershim.sock` which should be changed considering the deprecation of Docker as the underlying runtime.

Closes #455 

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [x] inline documentation builds (`cargo doc`)
- [x] version has been updated appropriately (`./version.sh`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Comment by Rishit-dagli** [comment]
I haven't updated the version yet, I think we would put this as a breaking change, right?

**Comment by kate-goldenring** [comment]
> I haven't updated the version yet, I think we would put this as a breaking change, right?

Good question. I think a patch version bump could be sufficient given that you can still configure the path in the Helm charts to point to docker.

**Comment by kate-goldenring** [comment]
Let's see how the e2e test go but this looks great @Rishit-dagli! If you are interested in updating the docs too, here is the associated doc: https://github.com/project-akri/akri-docs/blob/main/docs/user-guide/cluster-setup.md

**Comment by Rishit-dagli** [comment]
> Let's see how the e2e test go
This is from my fork, so we should also wait for the tests here. But here are the test results: https://github.com/Rishit-dagli/akri/actions/runs/3002656848 . MicroK8s-1.19 fails however the rest of them do pass.

**Comment by Rishit-dagli** [comment]
> If you are interested in updating the docs too, here is the associated doc: https://github.com/project-akri/akri-docs/blob/main/docs/user-guide/cluster-setup.md

Yep I had created https://github.com/project-akri/akri-docs/pull/52 updating the docs

**Review by kate-goldenring — APPROVED** [review]
This looks great! Once we remove EOL k8s versions from the matrix per https://github.com/project-akri/akri/pull/506#issuecomment-1239831597, i think this will be good to go. If you want to speed this along, feel free to remove k8s 1.16 from the matrix.

**Comment by Rishit-dagli** [comment]
> This looks great! Once we remove EOL k8s versions from the matrix per [#506 (comment)](https://github.com/project-akri/akri/pull/506#issuecomment-1239831597), i think this will be good to go. If you want to speed this along, feel free to remove k8s 1.16 from the matrix.

Gotcha, I pushed https://github.com/project-akri/akri/pull/508/commits/9212456676941067ad61890998d0425283b2084b which does that

**Pull request merged**
