### PR TITLE
Suffix usage slot to annotation key name

### PR DESCRIPTION
**Pull request by johnsonshih**
**What this PR does / why we need it**:

When allocate a device plugin, Agent adds the usage slot id to annotations to keep track of slot usage.  Currently, when a container uses multiple device plugins, all device plugins will set their values to the same annotation key and only information of one slot is recorded.  This PR suffix slot id to the annotation key name to keep all slot information.

The new format of annotation is:
akri.agent.slot-"slot id": "slot id"

In Agent, we parse the annotation keys use the format to avoid accidentally pulling in annotations with similar key name but are not set by Agent.

This PR is part of the fix for issue https://github.com/project-akri/akri/issues/492

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [x] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [x] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [x] inline documentation builds (`cargo doc`)
- [x] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

### CODE REVIEW

**Comment by adithyaj** [comment]
Johnson, I am unable to see any of the tests running for this PR. Were you able to see the tests run when you committed the changed? Can you also mark that `cargo clippy`/`cargo fmt`/`cargo build` etc from up top?

**Comment by adithyaj** [comment]
tests ran successfully 🎉 and this looks good to me; this should likely have a docs change as well when #560 & #561 resolves #492

**Review by adithyaj — APPROVED** [review]

**Comment by johnsonshih** [comment]
> tests ran successfully 🎉 and this looks good to me; this should likely have a docs change as well when #560 & #561 resolves #492

PR#560 is transparent to user.
PR#561 requires document change.

**Pull request merged**
